spring.application.name=demo
server.port=8080

logging.pattern.dateformat=hh:mm
spring.main.banner-mode=off
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:oracle:thin:@admindb_high?TNS_ADMIN=C:/Users/maxde/Downloads/Wallet_admindb
spring.datasource.username=ADMIN_MACRO
spring.datasource.password=AdminMacro2026!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
